### ISSUE TITLE
Question: cellRenderer Component Design Pattern

### ISSUE THREAD

**Issue by dephora** [supersabillon/ember-ag-grid#15]
Is there a proper design pattern for the cellRenderer Component style within an Ember component? Right now I'm using the cellRenderer Function method but I would prefer to pull the functions out of the `colDefs`.

Here is an example of what I'm doing using the typical 'function' style.

```
headerName: 'Phone',
field: 'phone',        
cellRenderer(params) {
  let phoneDiv = document.createElement('div');
  phoneDiv.className = `ag-phone ag-phone-small`;
  phoneDiv.innerHTML = `<div class="ag-phone-main">${params.value}</div> <div class="ag-
  phone-ext">ext. 3535</div>`
  return phoneDiv;
  }
},
```

Appreciate the library.

**Comment by supersabillon** [comment]
hey @dephora, yes you could definitely pull the functions out of colDefs.

In an app I work on, we have a utils folder under app, with a cell-helper.js file. From there we export different types of cell renderers, for example:

```
export default {

  currencyRenderer(params) {
    return formatMoney(params.value, { precision: 0 });
  },

  numberRenderer(params) {
    if (params.value == null || params.value === '') {
      return '';
    }
    return formatNumber(params.value, { precision: 0 });
  },

  percentRenderer(params) {
    return formatNumber(params.value, { precision: 0 }) + '%';
  }
};
```

Then we import this file and use it in the colDefs.
`import cellHelper from '../../../../utils/cell-helper';`

`cellRenderer: cellHelper.numberRenderer`

**Comment by dephora** [comment]
@supersabillon Oh that is a perfect idea, beautiful. Thanks a lot!
