### ISSUE TITLE
Question: Store to rowData

### ISSUE THREAD

**Issue by dephora** [supersabillon/ember-ag-grid#17]
Below is a working mock grid for testing, I have a few questions.

1. Is there a more 'Ember' way to get data from the store to the rowData (and to properties in general) than the following? It feels like I'm missing something in Ember that will better accomplish this.

2. I'm injecting the store as a service rather than relying on the route . If this is ill-advised for this library, I have no issues changing it as I believe all of my tables will be route specific. I imagine getting the store in the route and passing it in to the component would be the better solution so it's ready by the time the component / grid loads?

3. The following works fine but is it a disaster to do it this way? Would things be better handled in didInsertElement()? I believe all of my tables will be read only.

grid-example.js

```javascript
import Ember from 'ember';

export default Ember.Component.extend({

  store: Ember.inject.service(),

  gridOptions: {
    enableSorting: true,
    enableFilter: true,
    animateRows: true,

    columnDefs: [
      { headerName: "First Name", field: "firstName" },
      { headerName: "Last Name", field: "lastName" },
      { headerName: "Email", field: "email" },
      { headerName: "Twitter", field: "twitter" }
    ]
  },

  init() {

    this._super(...arguments);

    let rowData = [];
    this.get('store').findAll('friend').then(function(friends) {
      friends.forEach(function(friend) {
        let obj = {
          id: friend.get('id'),
          firstName: friend.get('firstName'),
          lastName: friend.get('lastName'),
          email: friend.get('email'),
          twitter: friend.get('twitter'),
        };
        rowData.pushObject(obj);
      });
    });
    this.gridOptions.rowData = rowData;
  },

});

```

Thanks in advance for any feedback.

**Comment by supersabillon** [comment]
hey @dephora, if the above works, then great!

Not sure if you have looked at the examples in the Dummy app. Most use static data, but some like Multiple Headers example pulls data from the route, and in the component I use a computed property.

**Comment by dephora** [comment]
@supersabillon - I didn't know there was a dummy app, mind linking it? I have no idea why I'm not seeing it anywhere. 

I've decided to use graphql as opposed to json-api but I'd like to see how you handled it. 

I appreciate your time!

**Comment by supersabillon** [comment]
@dephora I haven't uploaded the app, its on my todo list. But if you fork this repo, do `npm install` and then run `ember s` you should be able to run it locally.

**Comment by dephora** [comment]
@supersabillon Okay great - thanks so much.

**Comment by dephora** [comment]
@supersabillon 
The dummy app really helped, I see where I was going wrong with a few things.  Thanks again!
